Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,31 +26,23 @@ jobs:
         Write-Host "Determined Advanced Installer Path: $aiPath"
         echo "AI_PATH=$aiPath" >> $env:GITHUB_ENV
 
-    - name: Fetch all tags
-      run: git fetch --tags
-
-    - name: Extract Version from Tag
+    - name: Extract Version from AIP File
       id: extract-version
-      shell: pwsh
-      run: |
-        $latestTag = git describe --tags $(git rev-list --tags --max-count=1)
-        if ($latestTag -match 'v([0-9]+\.[0-9]+\.[0-9]+)') {
-            $version = $matches[1]
-            Write-Host "Extracted Version from Latest Tag: $version"
-            echo "VERSION=$version" >> $env:GITHUB_ENV
-        } else {
-            Write-Error "Tag format is invalid. Expected format: 'vX.X.X'."
-            exit 1
-        }
-
-    - name: Update Product Version in AIP File
-      id: update-version
       shell: pwsh
       run: |
         $aipPath = "AI Setup Project/Kurdish Digital Calendar.aip"
         if (Test-Path $aipPath) {
-            (Get-Content $aipPath) -replace 'Property="ProductVersion" Value="([0-9]+\.[0-9]+\.[0-9]+)"', "Property=`"ProductVersion`" Value=`"$env:VERSION`"" | Set-Content $aipPath
-            Write-Host "Updated Product Version in AIP file to: $env:VERSION"
+            $content = Get-Content $aipPath -Raw
+            Write-Host "Content successfully read from $aipPath"
+
+            if ($content -match 'Property="ProductVersion" Value="([0-9]+\.[0-9]+\.[0-9]+)"') {
+                $version = $matches[1]
+                Write-Host "Extracted Version: $version"
+                echo "VERSION=$version" >> $env:GITHUB_ENV
+            } else {
+                Write-Error "Version not found in AIP file."
+                exit 1
+            }
         } else {
             Write-Error "File not found: $aipPath"
             exit 1
